AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM template for the SpawtzCalendar app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Resources:
  CalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/SpawtzCalendar-1.0-SNAPSHOT.zip
      Handler: com.mduffin95.spawtzcalendar.Handler::handleRequest
      Runtime: java21
      Environment:
        Variables:
          BUCKET_NAME: !Ref CalendarBucket
          WEBSITE_BUCKET_NAME: !Ref StaticWebsiteBucket
      Events:
        ScheduledLambdaExecution:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 ? * * *) # 1pm every day
            Enabled: True
      Policies:
        - S3WritePolicy:
            BucketName: !Ref CalendarBucket
        - S3WritePolicy:
            BucketName: !Ref StaticWebsiteBucket

  CalendarBucket:
    Type: AWS::S3::Bucket

  CalendarBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CalendarBucket
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub arn:aws:s3:::${CalendarBucket}/calendar/v1/*

  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub arn:aws:s3:::${StaticWebsiteBucket}/*

Outputs:
  WebsiteURL:
    Description: URL for the static website
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL
